server:
  port: 9000

logging:
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} %-5level %C:%L - %m%n'
  file: logs/app.log
  level:
    org.springframework: debug

spring:
  batch:
    job:
      enabled: false

app:
  input: file:src/main/resources/file1.txt