// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: theater.proto

package com.protobuf;

public final class TheaterOuterClass {
  private TheaterOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_protobuf_Theater_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_protobuf_Theater_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\rtheater.proto\022\014com.protobuf\"(\n\007Theater" +
      "\022\014\n\004name\030\001 \001(\t\022\017\n\007address\030\002 \001(\tB\020\n\014com.p" +
      "rotobufP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_protobuf_Theater_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_protobuf_Theater_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_protobuf_Theater_descriptor,
        new String[] { "Name", "Address", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
