SELECT * FROM BATCH_JOB_EXECUTION;

SELECT * FROM BATCH_JOB_EXECUTION_CONTEXT ;

SELECT * FROM BATCH_JOB_EXECUTION_PARAMS ;

SELECT * FROM BATCH_JOB_INSTANCE ;

SELECT * FROM BATCH_STEP_EXECUTION ;

SELECT * FROM BATCH_STEP_EXECUTION_CONTEXT ;

SELECT * FROM USER_ENTITY ;