server.port: 9000

# changing /graphiql url to /app-ui
# graphiql.mapping: /app-ui

# changing default /graphql end point to /app
# graphql.servlet.mapping: /app

# property for graphql java client
graphql.client.url: http://localhost:9000/graphql