CREATE SEQUENCE DEPT_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

DROP TABLE DEPT IF EXISTS;

CREATE TABLE DEPT
(
 DEPTNO NUMBER(32)
,DNAME VARCHAR2(50)
,LOC VARCHAR2(50)
,CONSTRAINT DEPTNO_PK PRIMARY KEY(DEPTNO)
);

CREATE SEQUENCE EMP_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

DROP TABLE EMP IF EXISTS;

CREATE TABLE EMP
(
 EMPNO NUMBER(32)
,ENAME VARCHAR2(50)
,DEPTNO NUMBER(32) CONSTRAINT DEPTNO_FK REFERENCES DEPT(DEPTNO) ON DELETE CASCADE
,JOB VARCHAR2(50)
,SAL NUMBER(32)
,COMM NUMBER(32)
,MGR NUMBER(32) CONSTRAINT MGR_FK REFERENCES EMP(EMPNO)
,HIREDATE DATE
,ACTIVE BOOLEAN
,CONSTRAINT EMPNO_PK PRIMARY KEY(EMPNO)
);

CREATE SEQUENCE SALGRADE_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

DROP TABLE SALGRADE IF EXISTS;

CREATE TABLE SALGRADE
(
 HISAL NUMBER(32)
,LOSAL NUMBER(32)
,GRADE NUMBER(32)
);